name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Lint:
    # Lint任务
  UnitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 8.10.0
    - name: 安装依赖
      run: pnpm install
    - name: 跑测试
      run: pnpm run test