name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  UnitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.16.0'
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 8.10.0

      run: pnpm install  - name: 安装依赖
    - name: 跑测试
      run: pnpm run test